create table PRUEBA (
clave NUMBER(16,0) primary key,
disperso NUMBER(16,0),
concentrado NUMBER(16,0),
idisperso NUMBER(16,0),
iconcentrado NUMBER(16,0),
bconcentrado NUMBER(16,0));


DECLARE
I NUMBER(16,0);
R NUMBER(16,0);
BEGIN
FOR I IN 1..500000 LOOP
 R := DBMS_RANDOM.VALUE(1,1000000000);
 INSERT INTO PRUEBA VALUES(I, R, MOD(R,11), 1000000000-R, MOD(1000000000-R, 11),
MOD(2000000000-R, 11));
END LOOP;
END;
/

create index PID on prueba(IDISPERSO);

create index PIC on prueba(ICONCENTRADO);

create bitmap index PBC on prueba(BCONCENTRADO);

SET AUTOTRACE ON;
ALTER SESSION SET STATISTICS_LEVEL='ALL';

ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT COUNT(*) FROM PRUEBA WHERE CLAVE = 50000;
SELECT COUNT(*) FROM PRUEBA WHERE DISPERSO = 50000;
SELECT COUNT(*) FROM PRUEBA WHERE CONCENTRADO = 5;
SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO = 50000;
SELECT COUNT(*) FROM PRUEBA WHERE ICONCENTRADO = 5;
SELECT COUNT(*) FROM PRUEBA WHERE BCONCENTRADO = 5;

ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;
UPDATE PRUEBA SET DISPERSO = DISPERSO + 7;
ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;
UPDATE PRUEBA SET IDISPERSO = IDISPERSO + 7;

ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;
SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO BETWEEN 10000 AND 20000;


create index FIX on prueba(IDISPERSO+ICONCENTRADO);
