SET AUTOTRACE ON;
ALTER SESSION SET STATISTICS_LEVEL='ALL';

ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO BETWEEN 10000 AND 20000;


SET AUTOTRACE ON;
ALTER SESSION SET STATISTICS_LEVEL='ALL';

ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO+ICONCENTRADO BETWEEN 10000
AND 20000;