
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 28;
  public static final int POR = 11;
  public static final int CHAR = 33;
  public static final int STR = 36;
  public static final int ENTERO = 37;
  public static final int INT = 38;
  public static final int FOR = 7;
  public static final int NOIGUAL = 15;
  public static final int CP = 24;
  public static final int NOT = 16;
  public static final int MENORIGUAL = 19;
  public static final int AND = 21;
  public static final int IGUAL = 14;
  public static final int OR = 22;
  public static final int CH = 34;
  public static final int DIV = 12;
  public static final int CC = 27;
  public static final int IF = 2;
  public static final int MAYORIGUAL = 20;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOS = 10;
  public static final int MENOR = 17;
  public static final int IDENT = 41;
  public static final int MENOSUNARIO = 32;
  public static final int CLL = 26;
  public static final int REAL = 39;
  public static final int MAYOR = 18;
  public static final int ELSE = 3;
  public static final int PUNTO = 29;
  public static final int WHILE = 5;
  public static final int FLOAT = 40;
  public static final int STRING = 35;
  public static final int ALL = 25;
  public static final int AP = 23;
  public static final int PRINT = 6;
  public static final int LENGTH = 8;
  public static final int DO = 4;
  public static final int PYC = 31;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "PRINT",
  "FOR",
  "LENGTH",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "IGUAL",
  "NOIGUAL",
  "NOT",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "AND",
  "OR",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "CC",
  "AC",
  "PUNTO",
  "COMA",
  "PYC",
  "MENOSUNARIO",
  "CHAR",
  "CH",
  "STRING",
  "STR",
  "ENTERO",
  "INT",
  "REAL",
  "FLOAT",
  "IDENT"
  };
}

