import java_cup.runtime.*;

/* Terminales */
terminal 		INT, DOUBLE, PYC;
terminal String		IDENT;

/* No terminales */
non terminal			definicion;
non terminal 			variables_int, variables_double;

/* Precedencia */
precedence right INT, DOUBLE, IDENT;
precedence nonassoc PYC;

/* Gramatica */

definicion		::= INT variables_int PYC		
		  	  | DOUBLE variables_double PYC		
		  	  ;
		
variables_int		::= variables_int IDENT:i	{: System.out.print(i + ":int; "); :}
		  	| IDENT:i			{: System.out.print(i + ":int; "); :}
		  	;

variables_double	::= variables_double IDENT:i	{: System.out.print(i + ":double; "); :}
			  | IDENT:i			{: System.out.print(i + ":double; "); :}
			  ;
